name: .NET Core Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List directory contents
      run: ls -R  # Esto lista todos los archivos y carpetas en el repositorio

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Restore dependencies
      run: dotnet restore ./netcore/ExploringActions.sln

    - name: Build the project
      run: dotnet build ./netcore/ExploringActions.sln --configuration Release

    - name: Run unit tests
      run: dotnet test ./netcore/ExploringActions.sln --configuration Release
