name: .NET Core Unit Test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Cambia según la versión que estés utilizando

    - name: Restore dependencies
      run: dotnet restore ./netcore/ExploringActions/ExploringActions.csproj

    - name: Build
      run: dotnet build ./netcore/ExploringActions/ExploringActions.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test ./TestExploringActions/TestExploringActions.csproj --no-build --verbosity normal
